global:
  log_level: info

features:
  scuba:
    enabled: false
    enable_service_user: true

  bucket_notifications:
    enabled: false
    destinationAuth:
      type: none
      username: admin
      password: admin123

  utapi:
    enabled: false

cloudserver:
  image: ghcr.io/scality/cloudserver:7.70.62

vault:
  image: ghcr.io/scality/vault:7.73.0

backbeat:
  image: ghcr.io/scality/backbeat:9.0.12-federation

s3_metadata:
  image: ghcr.io/scality/metadata:7.70.47-standalone

scuba:
  image: ghcr.io/scality/scuba:1.1.0-preview.5-nodesvc-base

scuba_metadata:
  image: ghcr.io/scality/metadata:7.70.47-standalone

kafka:
  image: bitnami/kafka:3.4.0

zookeeper:
  image: bitnami/zookeeper:3.8.1

redis:
  image: redis:7

utapi:
  image: ghcr.io/scality/utapi:7.70.7
