worker_processes auto;

events {
    worker_connections 1024;
}

http {
    map $http_authorization $is_iam {
        default "0";
        "~Credential=[^/]+\/[^/]+\/[^/]+\/iam\/aws4_request" "1";
    }

    map $http_authorization $is_sts {
        default "0";
        "~Credential=[^/]+\/[^/]+\/[^/]+\/sts\/aws4_request" "1";
    }

    large_client_header_buffers 4 8224;

    proxy_cache off;
    tcp_nodelay on;
    underscores_in_headers on;
    ignore_invalid_headers off;

    upstream s3 {
        keepalive 256;
        server 127.0.0.1:8000 fail_timeout=0s max_fails=0;
    }

{{ if .Features.Scuba.Enabled }}
    upstream scuba {
        keepalive 256;
        server 127.0.0.1:9000;
    }
{{ end }}

    upstream iam {
        keepalive 256;
        server 127.0.0.1:8600;
    }

    upstream sts {
        keepalive 256;
        server 127.0.0.1:8800;
    }

    server {
        listen {{ .Nginx.HTTPPort }};
        listen {{ .Nginx.SSLPort }} ssl;

        server_tokens off;

        ssl_certificate /certs/s3-frontend.crt;
        ssl_certificate_key /certs/s3-frontend.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:10m;

        location / {
            proxy_request_buffering off;
            proxy_buffering off;

            proxy_pass http://s3;

            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header Connection "";

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-SSL-Cipher $ssl_cipher;
            proxy_set_header X-SSL-Protocol $ssl_protocol;

            proxy_send_timeout 300s;
            proxy_read_timeout 300s;

            client_max_body_size 0;

            if ($is_iam) {
                proxy_pass http://iam;
            }

            if ($is_sts) {
                proxy_pass http://sts;
            }

{{ if .Features.Scuba.Enabled }}
            location /_/sur/ {
                proxy_set_header Host $http_host;
                proxy_set_header proxy_path $uri;
                proxy_pass http://scuba/;
            }
{{ end }}
        }
    }
}
