---

name: tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: true
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Workbench up
        uses: ./
      - name: "Debug: SSH to runner"
        uses: scality/actions/action-ssh-to-runner@1.5.0
        with:
          tmate-server-host: ${{ secrets.TMATE_SERVER_HOST }}
          tmate-server-port: ${{ secrets.TMATE_SERVER_PORT }}
          tmate-server-rsa-fingerprint: ${{ secrets.TMATE_SERVER_RSA_FINGERPRINT }}
          tmate-server-ed25519-fingerprint: ${{ secrets.TMATE_SERVER_ED25519_FINGERPRINT }}
          detached: "true" # Set to "true" to enable detached mode if needed (optional, default is "false")
        timeout-minutes: 30
        continue-on-error: true
      - name: Test scuba query server
        run: curl http://localhost:18100
      - name: checkout scuba logs
        run: |
          docker logs workbench-scuba
          cat env/default/logs/scuba/*.log ;
          ls -l env/default/logs/
        if: always()
